export const provinciasMunicipios: Record<string, string[]> = {
  Azua: [
    "Azua",
    "Estebanía",
    "Guayabal",
    "Las Charcas",
    "Las Yayas de Viajama",
    "Padre Las Casas",
    "Peralta",
    "Pueblo Viejo",
    "Sabana Yegua",
    "Tábara Arriba",
  ],
  Baoruco: ["Galván", "Los Ríos", "Neiba", "Tamayo", "Villa Jaragua"],
  Barahona: [
    "Barahona",
    "Cabral",
    "El Peñón",
    "Enriquillo",
    "Fundación",
    "Jaquimeyes",
    "La Ciénaga",
    "Las Salinas",
    "Paraíso",
    "Polo",
    "Vicente Noble",
  ],
  Dajabón: ["Dajabón", "El Pino", "Loma de Cabrera", "Partido", "Restauración"],
  "Distrito Nacional": ["Santo Domingo de Guzmán"],
  Duarte: [
    "Arenoso",
    "Castillo",
    "Eugenio María de Hostos",
    "Las Guáranas",
    "Pimentel",
    "San Francisco de Macorís",
    "Villa Riva",
  ],
  "El Seibo": ["El Seibo", "Miches"],
  "Elías Piña": [
    "Bánica",
    "Comendador",
    "El Llano",
    "Hondo Valle",
    "Juan Santiago",
    "Pedro Santana",
  ],
  Espaillat: [
    "Cayetano Germosén",
    "Gaspar Hernández",
    "Jamao Al Norte",
    "Moca",
    "San Víctor",
  ],
  "Hato Mayor": ["El Valle", "Hato Mayor", "Sabana de La Mar"],
  "Hermanas Mirabal": ["Salcedo", "Tenares", "Villa Tapia"],
  Independencia: [
    "Cristóbal",
    "Duvergé",
    "Jimaní",
    "La Descubierta",
    "Mella",
    "Postrer Río",
  ],
  "La Altagracia": ["Higüey", "San Rafael del Yuma"],
  "La Romana": ["Guaymate", "La Romana", "Villa Hermosa"],
  "La Vega": ["Constanza", "Jarabacoa", "Jima Abajo", "La Vega"],
  "María Trinidad Sánchez": ["Cabrera", "El Factor", "Nagua", "Río San Juan"],
  "Monseñor Nouel": ["Bonao", "Maimón", "Piedra Blanca"],
  "Monte Cristi": [
    "Castañuelas",
    "Guayubín",
    "Las Matas de Santa Cruz",
    "Monte Cristi",
    "Pepillo Salcedo",
    "Villa Vásquez",
  ],
  "Monte Plata": [
    "Bayaguana",
    "Monte Plata",
    "Peralvillo",
    "Sabana Grande de Boyá",
    "Yamasá",
  ],
  Pedernales: ["Oviedo", "Pedernales"],
  Peravia: ["Baní", "Matanzas", "Nizao"],
  "Puerto Plata": [
    "Altamira",
    "Guananico",
    "Imbert",
    "Los Hidalgos",
    "Luperón",
    "Puerto Plata",
    "Sosúa",
    "Villa Isabela",
    "Villa Montellano",
  ],
  Samaná: ["Las Terrenas", "Samaná", "Sánchez"],
  "San Cristóbal": [
    "Bajos de Haina",
    "Cambita Garabitos",
    "Los Cacaos",
    "Sabana Grande de Palenque",
    "San Cristóbal",
    "San Gregorio de Nigua",
    "Villa Altagracia",
    "Yaguate",
  ],
  "San José de Ocoa": ["Rancho Arriba", "Sabana Larga", "San José de Ocoa"],
  "San Juan": [
    "Bohechío",
    "El Cercado",
    "Juan de Herrera",
    "Las Matas de Farfán",
    "San Juan",
    "Vallejuelo",
  ],
  "San Pedro de Macorís": [
    "Consuelo",
    "Guayacanes",
    "Los Llanos",
    "Quisqueya",
    "Ramón Santana",
    "San Pedro de Macorís",
  ],
  "Sanchez Ramírez": ["Cevicos", "Cotuí", "Fantino", "Villa La Mata"],
  Santiago: [
    "Baitoa",
    "Bisonó",
    "Jánico",
    "Licey al Medio",
    "Puñal",
    "Sabana Iglesia",
    "San José de Las Matas",
    "Santiago",
    "Tamboril",
    "Villa González",
  ],
  "Santiago Rodríguez": [
    "Monción",
    "San Ignacio de Sabaneta",
    "Villa Los Almácigos",
  ],
  "Santo Domingo": [
    "Boca Chica",
    "Los Alcarrizos",
    "Pedro Brand",
    "San Antonio de Guerra",
    "Santo Domingo Este",
    "Santo Domingo Norte",
    "Santo Domingo Oeste",
  ],
  Valverde: ["Esperanza", "Laguna Salada", "Mao"],
};

export const provincias = Object.keys(provinciasMunicipios).sort();
